/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SettingsRouteImport } from './routes/settings'
import { Route as ReportsRouteImport } from './routes/reports'
import { Route as OpdRouteImport } from './routes/opd'
import { Route as IpdRouteImport } from './routes/ipd'
import { Route as DoctorsRouteImport } from './routes/doctors'
import { Route as BillingRouteImport } from './routes/billing'
import { Route as IndexRouteImport } from './routes/index'
import { Route as PatientsRegisterRouteImport } from './routes/patients.register'
import { Route as MastersStateRouteImport } from './routes/masters.state'
import { Route as MastersPrefixRouteImport } from './routes/masters.prefix'
import { Route as MastersCityRouteImport } from './routes/masters.city'

const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const ReportsRoute = ReportsRouteImport.update({
  id: '/reports',
  path: '/reports',
  getParentRoute: () => rootRouteImport,
} as any)
const OpdRoute = OpdRouteImport.update({
  id: '/opd',
  path: '/opd',
  getParentRoute: () => rootRouteImport,
} as any)
const IpdRoute = IpdRouteImport.update({
  id: '/ipd',
  path: '/ipd',
  getParentRoute: () => rootRouteImport,
} as any)
const DoctorsRoute = DoctorsRouteImport.update({
  id: '/doctors',
  path: '/doctors',
  getParentRoute: () => rootRouteImport,
} as any)
const BillingRoute = BillingRouteImport.update({
  id: '/billing',
  path: '/billing',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const PatientsRegisterRoute = PatientsRegisterRouteImport.update({
  id: '/patients/register',
  path: '/patients/register',
  getParentRoute: () => rootRouteImport,
} as any)
const MastersStateRoute = MastersStateRouteImport.update({
  id: '/masters/state',
  path: '/masters/state',
  getParentRoute: () => rootRouteImport,
} as any)
const MastersPrefixRoute = MastersPrefixRouteImport.update({
  id: '/masters/prefix',
  path: '/masters/prefix',
  getParentRoute: () => rootRouteImport,
} as any)
const MastersCityRoute = MastersCityRouteImport.update({
  id: '/masters/city',
  path: '/masters/city',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/billing': typeof BillingRoute
  '/doctors': typeof DoctorsRoute
  '/ipd': typeof IpdRoute
  '/opd': typeof OpdRoute
  '/reports': typeof ReportsRoute
  '/settings': typeof SettingsRoute
  '/masters/city': typeof MastersCityRoute
  '/masters/prefix': typeof MastersPrefixRoute
  '/masters/state': typeof MastersStateRoute
  '/patients/register': typeof PatientsRegisterRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/billing': typeof BillingRoute
  '/doctors': typeof DoctorsRoute
  '/ipd': typeof IpdRoute
  '/opd': typeof OpdRoute
  '/reports': typeof ReportsRoute
  '/settings': typeof SettingsRoute
  '/masters/city': typeof MastersCityRoute
  '/masters/prefix': typeof MastersPrefixRoute
  '/masters/state': typeof MastersStateRoute
  '/patients/register': typeof PatientsRegisterRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/billing': typeof BillingRoute
  '/doctors': typeof DoctorsRoute
  '/ipd': typeof IpdRoute
  '/opd': typeof OpdRoute
  '/reports': typeof ReportsRoute
  '/settings': typeof SettingsRoute
  '/masters/city': typeof MastersCityRoute
  '/masters/prefix': typeof MastersPrefixRoute
  '/masters/state': typeof MastersStateRoute
  '/patients/register': typeof PatientsRegisterRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/billing'
    | '/doctors'
    | '/ipd'
    | '/opd'
    | '/reports'
    | '/settings'
    | '/masters/city'
    | '/masters/prefix'
    | '/masters/state'
    | '/patients/register'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/billing'
    | '/doctors'
    | '/ipd'
    | '/opd'
    | '/reports'
    | '/settings'
    | '/masters/city'
    | '/masters/prefix'
    | '/masters/state'
    | '/patients/register'
  id:
    | '__root__'
    | '/'
    | '/billing'
    | '/doctors'
    | '/ipd'
    | '/opd'
    | '/reports'
    | '/settings'
    | '/masters/city'
    | '/masters/prefix'
    | '/masters/state'
    | '/patients/register'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  BillingRoute: typeof BillingRoute
  DoctorsRoute: typeof DoctorsRoute
  IpdRoute: typeof IpdRoute
  OpdRoute: typeof OpdRoute
  ReportsRoute: typeof ReportsRoute
  SettingsRoute: typeof SettingsRoute
  MastersCityRoute: typeof MastersCityRoute
  MastersPrefixRoute: typeof MastersPrefixRoute
  MastersStateRoute: typeof MastersStateRoute
  PatientsRegisterRoute: typeof PatientsRegisterRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reports': {
      id: '/reports'
      path: '/reports'
      fullPath: '/reports'
      preLoaderRoute: typeof ReportsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/opd': {
      id: '/opd'
      path: '/opd'
      fullPath: '/opd'
      preLoaderRoute: typeof OpdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ipd': {
      id: '/ipd'
      path: '/ipd'
      fullPath: '/ipd'
      preLoaderRoute: typeof IpdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/doctors': {
      id: '/doctors'
      path: '/doctors'
      fullPath: '/doctors'
      preLoaderRoute: typeof DoctorsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/billing': {
      id: '/billing'
      path: '/billing'
      fullPath: '/billing'
      preLoaderRoute: typeof BillingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/patients/register': {
      id: '/patients/register'
      path: '/patients/register'
      fullPath: '/patients/register'
      preLoaderRoute: typeof PatientsRegisterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/masters/state': {
      id: '/masters/state'
      path: '/masters/state'
      fullPath: '/masters/state'
      preLoaderRoute: typeof MastersStateRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/masters/prefix': {
      id: '/masters/prefix'
      path: '/masters/prefix'
      fullPath: '/masters/prefix'
      preLoaderRoute: typeof MastersPrefixRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/masters/city': {
      id: '/masters/city'
      path: '/masters/city'
      fullPath: '/masters/city'
      preLoaderRoute: typeof MastersCityRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  BillingRoute: BillingRoute,
  DoctorsRoute: DoctorsRoute,
  IpdRoute: IpdRoute,
  OpdRoute: OpdRoute,
  ReportsRoute: ReportsRoute,
  SettingsRoute: SettingsRoute,
  MastersCityRoute: MastersCityRoute,
  MastersPrefixRoute: MastersPrefixRoute,
  MastersStateRoute: MastersStateRoute,
  PatientsRegisterRoute: PatientsRegisterRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
